[package]
name = "tiberius"
description = "A TDS (MSSQL) driver"
version = "0.2.0"
readme = "README.md"
repository = "https://github.com/steffengy/tiberius"
authors = ["Steffen Butzer <steffen.butzer@outlook.com>"]
keywords = ["tds", "mssql"]
license = "MIT/Apache-2.0"

[dependencies]
bitflags = "0.7.0"
byteorder = "1.0"
encoding = "0.2"
lazy_static = "0.2"
futures = "0.1.9"
tokio-core = "0.1.1"
futures-state-stream = "0.1"
chrono = { version = "0.2.25", optional=true }

[target.'cfg(windows)'.dependencies]
winapi = "0.2"
secur32-sys = "0.2"

[features]
default = ["chrono"]
