[package]
name = "tiberius"
description = "A TDS (MSSQL) driver"
version = "0.2.0"
readme = "README.md"
repository = "https://github.com/steffengy/tiberius"
authors = ["Steffen Butzer <steffen.butzer@outlook.com>"]
keywords = ["tds", "mssql"]
license = "MIT/Apache-2.0"

[dependencies]
bitflags = "0.7.0"
byteorder = "0.5"
lazy_static = "0.2"
log = "0.3"
futures = "0.1.6"
tokio-core = "0.1.1"

[dev-dependencies]
env_logger = "0.3"

[target.'cfg(windows)'.dependencies]
winapi = "0.2"
secur32-sys = "0.2"
