[package]
name = "tiberius"
description = "A TDS (MSSQL) driver"
version = "0.2.2"
readme = "README.md"
repository = "https://github.com/steffengy/tiberius"
authors = ["Steffen Butzer <steffen.butzer@outlook.com>"]
documentation = "https://docs.rs/tiberius/"
keywords = ["tds", "mssql"]
license = "MIT/Apache-2.0"

[dependencies]
bitflags = "0.8.0"
byteorder = "1.0"
bytes = "0.4.3"
encoding = "0.2"
lazy_static = "0.2"
futures = "0.1.9"
tokio-core = "0.1.1"
tokio-io = "0.1"
futures-state-stream = "0.1"
chrono = { version = "0.3", optional = true }
winauth = { version = "0.0.1" }
native-tls = { version = "0.1.4", optional = true }
tokio-tls = { version = "0.1", optional = true }

[features]
default = ["chrono", "tls"]
tls = ["tokio-tls", "native-tls"]

[target.'cfg(not(any(target_os = "windows", target_os = "macos")))'.dependencies]
openssl = "0.9.2"

[replace]
"tokio-tls:0.1.2" = { git = 'https://github.com/tokio-rs/tokio-tls' }
